#ifndef ENCRYPTOR_H
#define ENCRYPTOR_H

#include <QObject>

class Encryptor : public QObject
{
    Q_OBJECT
public:
    explicit Encryptor(QObject *parent = nullptr);

    uchar* getRandomKey(int size);
    void derivePassword(QString password, uchar* salt, uchar* storedPDKOut, uchar* encPDKOut);

    int encryptAES_256_CBC(uchar* input, size_t inSize, uchar* key, uchar* iv, uchar* output);
    int decryptAES_256_CBC(uchar* input, size_t inSize, uchar* key, uchar* iv, uchar* output);
    int sha256(uchar* input, size_t inSize, uchar* output, uint* outSize);

signals:
    void errorOccured(int id);

private:
    bool _generateRandomBytes(uchar* array, size_t size);
    int _derivePassword(char* password, uchar* salt, size_t size, uchar* output);
    void _splitArrayHalf(uchar* input, size_t inSize, uchar* half1, uchar* half2);
    void _handleErrorMessage(int errorCode);

    //Sizes of the randomly generated bytes
    size_t _derivedKeySize = 64;
    size_t _ivSize = 16;        //Size of an AES-256-CBC block
    size_t _encKeySize = 32;

    int _passIterations = 100000;
};

#endif // ENCRYPTOR_H
